/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package joker;

import java.util.Arrays;

public class App {
    public static Joker getJoker() {
        WitzeListe liste = new WitzeListe(Arrays.asList(
            new Witz("demo 1"), 
            new Witz("demo 2"),
            new Witz("demo 3"))
        );

        ConsoleAusgabe ausgabe = new ConsoleAusgabe();
        return new Joker(liste, ausgabe);
    }

    public static void main(String[] args) {
        Joker joker = getJoker();
        joker.tellJoke();
    }
}
