/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package joker;

public class App {
    public static Joker getJoker() {
        WitzeListe liste = new WitzeListe();
        liste.add(new Witz("demo 1"));

        ConsoleAusgabe ausgabe = new ConsoleAusgabe();
        return new Joker(liste, ausgabe);
    }

    public static void main(String[] args) {
        Joker joker = getJoker();
        joker.tellJoke();
    }
}
